# https://github.com/marketplace/actions/auto-update
name: autoupdate
on:
 push:
   branches:
     - develop # Whenever the base changes, this action should run

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-20.04
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          PR_FILTER: 'auto_merge'
