name: Release Prep
on:
  schedule:
    # Every day at 12am PST / 3am EST
    - cron: '0 7 * * *'

jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install ge_releaser
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          # Install release tool in a separate repo than GE
          pushd ..
          git clone https://github.com/superconductive/ge_releaser.git
          pip install -e ge_releaser
          popd
      - name: Create PR
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          # A release PR will only be drafted if the current date matches the release schedule
          ge_releaser prep --file=./.github/release_schedule.json
